// GETTERS
export const LAST_ORDERS = 'order/LAST_ORDERS';
export const INSERTED_ORDER = 'order/INSERTED_ORDER';
export const FILTERED_ORDERS = 'order/FILTERED_ORDERS';
export const CUSTOMER_ID = 'order_CUSTOMER_ID';
export const HAS_PROFORMA = 'order/HAS_PROFORMA';
export const ORDER_SPEC_FORM_IS_ACTIVE = 'order/ORDER_SPEC_FORM_IS_ACTIVE';
export const INSERTED_SPECS = 'order/INSERTED_SPECS';

// MUTATIONS

export const MUTATE_LAST_ORDERS = 'order/MUTATE_LAST_ORDERS';
export const MUTATE_INSERTED_ORDER = 'order/MUTATE_INSERTED_ORDER';
export const MUTATE_FILTERED_ORDER = 'order/MUTATE_FILTERED_ORDER';
export const MUTATE_CUSTOMER_ID = 'order/MUTATE_CUSTOMER_ID';
export const MUTATE_HAS_PROFORMA = 'order/MUTATE_HAS_PROFORMA';
export const MUTATE_SPEC_FORM_IS_ACTIVE = 'order/MUTATE_SPEC_FORM_IS_ACTIVE';
export const MUTATE_INSERTED_SPECS = 'order/MUTATE_INSERTED_SPECS';
// ACTIONS

export const ACTION_INSERT_ORDER = 'order/ACTION_INSERT_ORDER';
export const ACTION_FILTERED_ORDERS = 'order/ACTION_FILTERED_ORDERS';
export const ACTION_LAST_ORDERS = 'order/ACTION_LAST_ORDERS';
export const ACTION_CUSTOMER_ID = 'order/ACTION_CUSTOMER_ID';
export const ACTION_HAS_PROFORMA = 'order/ACTION_HAS_PROFORMA';
export const ACTION_INSERT_SPEC = 'order/ACTION_INSERT_SPEC';

