// GETTERS
export const INCOME_ID = 'income/INCOME_ID';
export const INSERTED_INCOME = 'income/INSERTED_INCOME';
export const EXPANDED_INCOME_ID = 'income/EXPANDED_INCOME_ID';
export const INCOME_FILTER_FORM = 'income/INCOME_FILTER_FORM';
export const FILTERED_INCOMES = 'income/FILTERED_INCOMES';
export const INCOME_ROWS = 'income/INCOME_ROWS';
export const LOADING_INCOME_ROWS = 'income/LOADING_INCOME_ROWS';
export const LOADING_FILTERED_INCOMES = 'income/LOADING_FILTERED_INCOMES';
export const INCOME_ROW_FORM_IS_ACTIVE = 'income/INCOME_ROW_FORM_IS_ACTIVE';
export const INCOME_HOLDER_FORM_STEP = 'income/INCOME_HOLDER_FORM_STEP';
export const UPSERTED_INCOME_ROW = 'income/UPSERTED_INCOME_ROW';
export const CUSTOMER_UNPAID_PROFORMAS = 'income/CUSTOMER_UNPAID_PROFORMAS';

// MUTATIONS
export const MUTATE_INCOME_ID = 'income/MUTATE_INCOME_ID';
export const MUTATE_INSERTED_INCOME = 'income/MUTATE_INSERTED_INCOME';
export const MUTATE_EXPANDED_INCOME_ID = 'income/MUTATE_EXPANDED_INCOME_ID';
export const MUTATE_INCOME_FILTER_FORM = 'income/MUTATE_INCOME_FILTER_FORM';
export const MUTATE_FILTERED_INCOMES = 'income/MUTATE_FILTERED_INCOMES';
export const MUTATE_INCOME_ROWS = 'income/MUTATE_INCOME_ROWS';
export const MUTATE_LOADING_FILTERED_INCOME = 'income/MUTATE_LOADING_FILTERED_INCOME';
export const MUTATE_LOADING_INCOME_ROWS = 'income/MUTATE_LOADING_INCOME_ROWS';
export const MUTATE_ASSIGNMENT_FORM_IS_ACTIVE = 'income/MUTATE_ASSIGNMENT_FORM_IS_ACTIVE';
export const MUTATE_INCOME_HOLDER_FORM_STEP = 'income/MUTATE_INCOME_HOLDER_FORM_STEP';
export const MUTATE_UPSERTED_INCOME_ROW = 'income/MUTATE_UPSERTED_INCOME_ROW';
export const MUTATE_CUSTOMER_UNPAID_PROFORMAS = 'income/MUTATE_CUSTOMER_UNPAID_PROFORMAS';

// ACTIONS
export const ACTION_UPSERT_INCOME = 'income/ACTION_INSERT_INCOME';
export const ACTION_UPSERT_INCOME_ROW = 'income/ACTION_INSERT_INCOME_ROW';
export const ACTION_UPDATE_FILTERED_INCOMES = 'income/ACTION_UPDATE_FILTERED_INCOMES';
export const ACTION_UPDATE_INCOME_ROWS = 'income/ACTION_UPDATE_INCOME_ROWS';
export const ACTION_UPDATE_CUSTOMER_UNPAID_PROFORMAS = 'income/ACTION_UPDATE_CUSTOMER_UNPAID_PROFORMAS';
