// GETTERS
export const LAST_ORDERS = 'order/LAST_ORDERS';
export const INSERTED_ORDER = 'order/INSERTED_ORDER';
export const FILTERED_ORDERS = 'order/FILTERED_ORDERS';
export const CUSTOMER_ID = 'order_CUSTOMER_ID';
export const NO_PROFORMA = 'order/NO_PROFORMA';
export const ORDER_SPEC_FORM_IS_ACTIVE = 'order/ORDER_SPEC_FORM_IS_ACTIVE';
export const ORDER_SPECS = 'order/ORDER_SPECS';
export const ORDER_FILTER_FORM = 'order/ORDER_FILTER_FORM';
export const LOADING_FILTERED_ORDERS = 'order/LOADING_FILTERED_ORDERS';
export const LOADING_ORDER_SPECS = 'order/LOADING_ORDER_SPECS';
export const SELECTED_ORDER_ID = 'order/SELECTED_ORDER_ID';

// MUTATIONS
export const MUTATE_LAST_ORDERS = 'order/MUTATE_LAST_ORDERS';
export const MUTATE_INSERTED_ORDER = 'order/MUTATE_INSERTED_ORDER';
export const MUTATE_FILTERED_ORDER = 'order/MUTATE_FILTERED_ORDER';
export const MUTATE_CUSTOMER_ID = 'order/MUTATE_CUSTOMER_ID';
export const MUTATE_HAS_PROFORMA = 'order/MUTATE_HAS_PROFORMA';
export const MUTATE_SPEC_FORM_IS_ACTIVE = 'order/MUTATE_SPEC_FORM_IS_ACTIVE';
export const MUTATE_ORDER_SPECS = 'order/MUTATE_ORDER_SPECS';
export const MUTATE_DELETED_ORDER = 'order/MUTATE_DELETED_ORDER';
export const MUTATE_ORDER_FILTER_FORM = 'order/MUTATE_ORDER_FILTER_FORM';
export const MUTATE_LOADING_FILTERED_ORDERS = 'order/MUTATE_LOADING_FILTERED_ORDERS';
export const MUTATE_LOADING_ORDER_SPECS = 'order/MUTATE_LOADING_ORDER_SPECS';
export const MUTATE_SELECTED_ORDER_ID = 'order/MUTATE_SELECTED_ORDER_ID';

// ACTIONS
export const ACTION_INSERT_ORDER = 'order/ACTION_INSERT_ORDER';
export const ACTION_FILTERED_ORDERS = 'order/ACTION_FILTERED_ORDERS';
export const ACTION_LAST_ORDERS = 'order/ACTION_LAST_ORDERS';
export const ACTION_CUSTOMER_ID = 'order/ACTION_CUSTOMER_ID';
export const ACTION_HAS_PROFORMA = 'order/ACTION_HAS_PROFORMA';
export const ACTION_ORDER_SPECS = 'order/ACTION_ORDER_SPECS';
export const ACTION_INSERT_SPEC = 'order/ACTION_INSERT_SPEC';
export const ACTION_DELETE_ORDER = 'order/ACTION_DELETE_ORDER';
export const ACTION_ORDER_FILTER_FORM = 'order/ACTION_ORDER_FILTER_FORM';

