// GETTERS
export const LAST_ORDERS = 'order/LAST_ORDERS';
export const SELECTED_ORDER_ID = 'order/SELECTED_ORDER_ID';
export const UPSERTED_ORDER = 'order/UPSERTED_ORDER';
export const ORDER_SPEC_FORM_IS_ACTIVE = 'order/ORDER_SPEC_FORM_IS_ACTIVE';
export const ORDER_SPECS = 'order/ORDER_SPECS';
export const ORDER_FILTER_FORM = 'order/ORDER_FILTER_FORM';
export const FILTERED_ORDERS = 'order/FILTERED_ORDERS';
export const LOADING_FILTERED_ORDERS = 'order/LOADING_FILTERED_ORDERS';
export const LOADING_ORDER_SPECS = 'order/LOADING_ORDER_SPECS';
export const CUSTOMER_ID = 'order_CUSTOMER_ID';

// MUTATIONS
export const MUTATE_LAST_ORDERS = 'order/MUTATE_LAST_ORDERS';
export const MUTATE_SELECTED_ORDER_ID = 'order/MUTATE_SELECTED_ORDER_ID';
export const MUTATE_UPSERTED_ORDER = 'order/MUTATE_UPSERTED_ORDER';
export const MUTATE_SPEC_FORM_IS_ACTIVE = 'order/MUTATE_SPEC_FORM_IS_ACTIVE';
export const MUTATE_FILTERED_ORDER = 'order/MUTATE_FILTERED_ORDER';
export const MUTATE_ORDER_FILTER_FORM = 'order/MUTATE_ORDER_FILTER_FORM';
export const MUTATE_ORDER_SPECS = 'order/MUTATE_ORDER_SPECS';
export const MUTATE_DELETED_ORDER = 'order/MUTATE_DELETED_ORDER';
export const MUTATE_LOADING_FILTERED_ORDERS = 'order/MUTATE_LOADING_FILTERED_ORDERS';
export const MUTATE_LOADING_ORDER_SPECS = 'order/MUTATE_LOADING_ORDER_SPECS';
export const MUTATE_CUSTOMER_ID = 'order/MUTATE_CUSTOMER_ID';

// ACTIONS
export const ACTION_UPSERT_ORDER = 'order/ACTION_UPSERT_ORDER';
export const ACTION_FILTER_ORDERS = 'order/ACTION_FILTER_ORDERS';
export const ACTION_LAST_ORDERS = 'order/ACTION_LAST_ORDERS';
export const ACTION_ORDER_SPECS = 'order/ACTION_ORDER_SPECS';
export const ACTION_UPSERT_SPEC = 'order/ACTION_UPSERT_SPEC';
export const ACTION_DELETE_ORDER = 'order/ACTION_DELETE_ORDER';

