// GETTERS
export const PROFORMA_ORDER_ID = 'proforma/PROFORMA_ORDER_ID';
export const PROFORMA_ID = 'proforma/PROFORMA_ID';
export const PROFORMA_ORDER_SPECS = 'proforma/PROFORMA_ORDER_SPECS';
export const PROFORMA_SPECS = 'proforma/PROFORMA_SPECS';
export const PROFORMA_FORMS_SPECS = 'proforma/PROFORMA_FORMS_SPECS';
export const PROFORMA_SPEC_FORM_IS_ACTIVE = 'proforma/PROFORMA_SPEC_FORM_IS_ACTIVE';
export const PROFORMA_SPEC_PREVIEW_IS_ACTIVE = 'proforma/PROFORMA_SPEC_PREVIEW_IS_ACTIVE';
export const PROFORMA='proforma/PROFORMA';
export const SNACKBAR='proforma/SNACKBAR';
export const SNACKBAR_MSG='proforma/SNACKBAR_MSG';

// MUTATIONS
export const MUTATE_PROFORMA_ORDER_ID = 'proforma/MUTATE_PROFORMA_ORDER_ID';
export const MUTATE_PROFORMA_ID = 'proforma/MUTATE_PROFORMA_ID';
export const MUTATE_PROFORMA_ORDER_SPECS = 'proforma/MUTATE_PROFORMA_ORDER_SPECS';
export const MUTATE_PROFORMA_SPECS = 'proforma/MUTATE_PROFORMA_SPECS';
export const MUTATE_PROFORMA_FORM_SPECS = 'proforma/MUTATE_PROFORMA_FORM_SPECS';
export const MUTATE_PROFORMA_SPEC_FORM_IS_ACTIVE = 'proforma/MUTATE_PROFORMA_SPEC_FORM_IS_ACTIVE';
export const MUTATE_PROFORMA_SPEC_PREVIEW_FORM_IS_ACTIVE = 'proforma/MUTATE_PROFORMA_SPEC_PREVIEW_FORM_IS_ACTIVE';
export const MUTATE_PROFORMA='proforma/MUTATE_PROFORMA';
export const MUTATE_RESET_PROFORMA_FORMS = 'proforma/MUTATE_RESET_PROFORMA_FORM';
export const MUTATE_SNACKBAR = 'proforma/MUTATE_SNACKBAR';
export const MUTATE_SNACKBAR_MSG = 'proforma/MUTATE_SNACKBAR_MSG';

// ACTIONS
export const ACTION_UPDATE_PROFORMA_ORDER_SPECS = 'proforma/ACTION_UPDATE_PROFORMA_ORDER_SPECS';
export const ACTION_UPDATE_PROFORMA = 'proforma/ACTION_UPDATE_PROFORMA';
export const ACTION_UPDATE_PROFORMA_SPECS = 'proforma/ACTION_UPDATE_PROFORMA_SPECS';
export const ACTION_INSERT_PROFORMA = 'proforma/ACTION_INSERT_PROFORMA';
export const ACTION_INSERT_PROFORMA_SPEC_BULK = 'proforma/ACTION_INSERT_PROFORMA_SPEC_BULK';
